src/account_x/x_account_controller.ts

Closes #383
I've tested the `archiveBuild` method using a small test archive

fix: `XAccountController` should use streaming in `archiveBuild`

---

src/main.ts
src/preload.ts
src/renderer/src/main.ts
src/renderer/src/views/x/AccountXView.vue

We open native dialogs with Electron's `dialog.showMessageBoxSync`. This supports passing in `message` but also `detail`, which is smaller text beneath the message. This PR adds support for using `detail`.
For example, when you're in open mode and you start Cyd, it used to pop this up:
Now it pops this up:

Make message dialogs look better

---

src/account_x.test.ts
src/account_x/types.ts
src/account_x/x_account_controller.ts
testdata/XAPIUserTweetsAndRepliesLinks.json
testdata/XAPIUserTweetsAndRepliesMedia.json

Hey @SaptakS this fixes the "Figure out issue with downloading of videos" step in #393. Here's how I did it:
In a test X account, I posted a tweet with an image, and another tweet with a video. Then using Burp Suite, I logged into my test X account and loaded my test account's replies feed. In Burp Suite, I found the `UserTweetsAndReplies` API request:
I copied the JSON into a text editor and formatted it so I could see exactly what's in each `tweets['legacy']['media']` object. I also saved this as `testdata/XAPIUserTweetsAndRepliesMedia.json`, so I could later write a test using it.
Based on what I found, I started with updating the typescript interfaces to support the media fields we need. In `src/account_x/types.ts`, I edited `XAPILegacyTweet` to support the `media` field. I made sure …

Support for indexing video (and fix indexing URLs)

---

src/cyd-api-client.ts
src/renderer/src/App.vue
src/renderer/src/modals/SignInModal.vue

This PR updates the Cyd server with usage data in compliance with Lockdown Systems' Privacy Policy. An API request gets sent after the Plausible analytics data to Cyd server:
When you run this PR against https://github.com/lockdown-systems/cyd-server/pull/128 you'll see:
```
api-1         | 02-17 20:45 werkzeug     INFO     172.19.0.1 - - [17/Feb/2025 20:45:30] "POST /user/activity HTTP/1.1" 200 -
```

if logged in, update user activity

---

package-lock.json
package.json
src/account_x/x_account_controller.ts
src/renderer/src/views/x/XWizardMigrateBluesky.vue
src/shared_types/x.ts

One tester pointed out it was confusing that only a relatively small number of tweets could be migrated compared to the estimate of the total tweets in the right sidebar.
This PR adds chart.js to graph the tweets and explain what can and can't be migrated. It tells you the total number of tweets in the local database, how many have already been migrated, how many are retweets, and how many are replies to other users.
Also, it's pretty. Since this adds chart.js, I'd be into adding data viz all over where it's appropriate.

Add more information about your tweets before you migrate to Bluesky

---

archive-static-sites/x-archive/src/components/TweetComponent.vue
src/account_x.test.ts
src/account_x/x_account_controller.ts
testdata/XAPIUserTweetsAndRepliesMedia.json

Fixes #421 
So seems like X saves the GIFs are video files when uploaded (or added from it's interface) as a part of the post. What actually gets rendered is a MP4 file instead of GIF, which is slightly sad since it would have been nice to save a GIF file for migrations elsewhere. However I have gone ahead and made changes to save the MP4 file created by twitter for the GIF.
This should help in storing the video information instead of just a JPG. I have also added tests and modified the local archive template code to render it correctly.

Fixes gif downloading when building the archive

---

archive-static-sites/facebook-archive/src/components/PostComponent.vue
archive-static-sites/facebook-archive/src/types.ts
archive-static-sites/facebook-archive/src/views/PostsView.vue
src/account_facebook/facebook_account_controller.ts
src/account_facebook/types.ts

Stacked PR on #411
Closes #407 
This adds the repost data that exists in the JSON FB export to the database and displays it on the archive app:

[facebook 3] support reposts in Facebook archiving

---

src/account_x.test.ts
src/account_x/types.ts
src/account_x/x_account_controller.ts
src/renderer/src/App.vue
src/renderer/src/view_models/XViewModel.ts
src/renderer/src/views/x/XJobStatusComponent.vue
src/renderer/src/views/x/XView.vue
testdata/XAPIUserTweetsAndRepliesError.json

Fixes #432.
Also fixes #416, which I just realized was introduced in #384.
I also merged #434 and #430 into this branch, so we should review/merge those first.
For some reason, X returned a tweet (technically a RT) with entities that had `urls` that looked like this:
```
"urls": [
{
"display_url": "t.co",
"url": "https://t.co/",
"indices": [
130,
143
]
}
],
```
While indexing, this now only saves URLs from tweets if all of the correct fields are present.
During indexTweets, X sometimes responds with 429 even when it is not really rated limited. This leads the indexing to stop early because it cannot find the retry button. This PR checks to make sure this is not the case before looking for the retry button, so the indexing doesn't stop early. I think this should make indexing more robust. …

Various X bug fixes

---

src/account_x/x_account_controller.ts

In `blueskyMigrateTweetBuildRecord`, I've removed the try/catch blocks around `agent.uploadBlob` so that if it throws an error, the code in `blueskyMigrateTweet` can catch it and handle it like it does the other rate limit errors.
I've also made a `handleBlueskyAPIError` function to re-use, to avoid repeating myself each time we need to check for a Bluesky API error (uploading media in `blueskyMigrateTweetBuildRecord`, posting to Bluesky, posting the follow-up post to Bluesky, deleting a post from Bluesky).
Unfortunately, this PR is kind of hard to test. We'd have to trigger Bluesky rate limits, which means posting thousands of things to Bluesky. I did test it myself and successfully get a rate limit for posting (I still need to wait an hour for it to expire) but it's more difficult for …

Handle rate limits while uploading media

---

docs/docusaurus.config.ts

So we can get private analytics on how much people are using the docs.

Add plausible to docs site

---

src/account_x/x_account_controller.ts
src/renderer/src/views/x/XWizardMigrateBluesky.vue

Fixes #447 
This change just strips the @ from the beginning if the bluesky handle startswith @ and then sends the authorization request with the modified handle.
@micahflee I have not tested this with an actual bluesky account.

Allow bluesky handle input to start with @

---

src/renderer/src/view_models/XViewModel.ts

When helping someone delete all their many thousands of DMs, I found that a 2 second timeout wasn't enough for the DM conversations to load. This increases it to 10 seconds, which seems to work fine.

When loading the DMs page to delete DMs, increase the timeout

---

src/renderer/src/util.ts
src/renderer/src/view_models/FacebookViewModel.ts
src/renderer/src/view_models/XViewModel.ts
src/renderer/src/views/x/XView.vue

For our error reports, we've been collecting exception data just by running `toString()` on the Error, like:  `{ exception: (e as Error).toString() }`. But this ends up with error data like this:
```json
{
"exception": "TypeError: Cannot create property 'logs' on boolean 'true'"
}
```
It would be much better if we could have actual stack traces, to pinpoint the file and line number where the error occurred. This PR adds a `formatError` function that returns a string that includes both the error message and the stack trace, and it updates all of the error report calls to use this instead.

Include full stack trace on errors

---

src/account_facebook/facebook_account_controller.ts
src/account_facebook/ipc.ts
src/preload.ts
src/renderer/src/main.ts
src/renderer/src/util_facebook.ts
src/renderer/src/view_models/FacebookViewModel.ts
src/renderer/src/views/facebook/FacebookView.vue
src/renderer/src/views/facebook/FacebookWizardArchiveOptionsPage.vue
src/renderer/src/views/facebook/FacebookWizardDeleteOptionsPage.vue
src/renderer/src/views/facebook/FacebookWizardImportPage.vue
src/shared_types/account.ts
src/shared_types/facebook.ts

Closes #465
This implements a few more of the required pages for Facebook after importing your Meta export:

facebook: add `Delete` and `Archive` options

---

src/renderer/src/view_models/BaseViewModel.ts

Hopefully fixes #466, but it's hard to tell because it's hard to reliably reproduce.
I believe the GUEST_VIEW_MANAGER_CALL error happens because we're trying to load a URL in the `<webview>` before something is fully initialized (either the webview itself, the MITM CA, or something).
Our `BaseViewModel.loadURL` function tries 3 times before erroring it, but it doesn't wait between retries. This sleeps 1 second between retries, which hopefully will give the webview or MITM proxy, or whatever, enough time to finish initializing.
See https://github.com/lockdown-systems/cyd/issues/466#issuecomment-2770640629 for more details.

If loading a URL fails, wait 1 second before retrying loading the URL

---

scripts/clean.js
src/account_x/x_account_controller.ts
src/renderer/src/view_models/XViewModel.ts
src/renderer/src/views/x/XWizardReviewPage.vue

Hopefully this will fix #428 and #492.
This PR should make the performance of using the X platform waaaaaay better.
Before, when an X account tab was loaded, it created an `XViewModel` object, which runs `refreshDatabaseStats` to update its internal state of the database stats. This included a call to the `getDeleteReviewStats` IPC function, which is used for the review page when you're getting ready to delete. It basically does some heavy database queries to learn the number of tweets, retweets, likes, etc. it's going to delete, based on your settings.
But `getDeleteReviewStats` only needs to get run when you get to the review page, not when a `XViewModel` is initialized, and not every time `refreshDatabaseStats` is called either.
This PR removes `getDeleteReviewStats` from …

Make X SQL queries considerably more efficient

---

scripts/make-linux-release.sh

Oops. This was removed in #489, but now that we're making a release, it turns out it's necessary for linux,

Add scripts/make-linux-release.sh back

---

src/renderer/src/view_models/XViewModel.ts

Fixes #456. Or at least, I hope it should. It is not reliably reproducible.
The `XViewModel.login` function loads the login page and waits until the user is successfully logged in; then called `XViewModel.graphqlGetViewerUser` to get user info like username, user ID, profile image, etc.
The `graphqlGetViewerUser` function makes a GraphQL request. The error we're getting is sometimes this request fails and returns null. So this PR tries to make this more robust by:
- Trying 3 times instead of just once, waiting 1 second between tries
- Forcing a load of the X homepage before each try -- it only makes sense to make the GraphQL request from within the context of an X page that is fully loaded, so we make sure to fully load it each time

Make graphqlGetViewerUser try 3 times

---

src/renderer/src/view_models/BaseViewModel.ts
src/renderer/src/view_models/XViewModel.ts

Fixes #514.
The first bug report in #514 was bizarre because it occurred while loading `about:blank` and the state was `FinishedRunningJobs`. Why would this happen?
Here's the entire `FinishedRunningJobs` state, from `XViewModel`:
```ts
case State.FinishedRunningJobs:
this.showBrowser = false;
this.instructions = `
All done!
**Here's what I did.**`;
await this.loadURL("about:blank");
this.state = State.FinishedRunningJobsDisplay;
break;
```
It sets the instruction, loads `about:blank`, and then switches the state to `FinishedRunningJobsDisplay`. So this must have occurred in this `loadURL` call.
So I looked in `BaseViewModel` for `loadURL` and noticed this:
```ts
async loadBlank() {
this.log("loadBlank");
const webview = this.getWebview();
if (webview) {
// Note: We need to wait for the …
```

Fix `GUEST_VIEW_MANAGER_CALL` error for good (I hope)

---

src/account_x/x_account_controller.ts

This is modifying the logic for imports such that we do not error if the target folder already exists, we just use it. Closes #556. Closes #559.

fix: use existing folder if it exists
